tabs:
  webhook:
    display: 'Webhook'
    sections:
      -
        fields:
          -
            handle: webhook_url
            field:
              display: 'Webhook URL'
              type: text
              read_only: false
      -
        fields:
          -
            handle: events.entry_saved.enabled
            field:
              display: 'Entry Saved Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.entry_deleted.enabled
            field:
              display: 'Entry Deleted Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.collection_saved.enabled
            field:
              display: 'Collection Saved Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.collection_deleted.enabled
            field:
              display: 'Collection Deleted Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.taxonomy_saved.enabled
            field:
              display: 'Taxonomy Saved Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.taxonomy_deleted.enabled
            field:
              display: 'Taxonomy Deleted Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.term_saved.enabled
            field:
              display: 'Term Saved Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.term_deleted.enabled
            field:
              display: 'Term Deleted Event'
              type: toggle
              read_only: false
              width: 25
