tabs:
  webhook:
    display: 'Webhook'
    sections:
      -
        display: 'Webhook (POST Request)'
        fields:
          -
            handle: webhook_url
            field:
              display: 'URL'
              type: text
              read_only: false
      -
        display: 'Webhook Authentication Header'
        fields:
          -
            handle: webhook_auth_header_key
            field:
              display: 'Header'
              type: text
              read_only: false
              width: 50
          -
            handle: webhook_auth_header_value
            field:
              display: 'Value'
              type: text
              read_only: false
              width: 50
      -
        display: 'Webhook Events'
        fields:
          -
            handle: events.entry_saved.enabled
            field:
              display: 'Entry Saved Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.entry_deleted.enabled
            field:
              display: 'Entry Deleted Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.collection_saved.enabled
            field:
              display: 'Collection Saved Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.collection_deleted.enabled
            field:
              display: 'Collection Deleted Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.taxonomy_saved.enabled
            field:
              display: 'Taxonomy Saved Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.taxonomy_deleted.enabled
            field:
              display: 'Taxonomy Deleted Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.term_saved.enabled
            field:
              display: 'Term Saved Event'
              type: toggle
              read_only: false
              width: 25
          -
            handle: events.term_deleted.enabled
            field:
              display: 'Term Deleted Event'
              type: toggle
              read_only: false
              width: 25
